[features]
seeds = false
skip-lint = false

[programs.localnet]
battleflip = "mWishTAXRe8gdGcqF6VqYW3JL1CkHU5waMfkM9VTVmg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"